FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app
COPY . .
RUN adduser --system --group --shell /bin/sh auser \
 && mkdir /home/auser/bin
RUN mkdir -m 777 media
RUN mkdir -m 777 staticfiles
RUN chmod +x ./start.sh
USER auser
EXPOSE 8000
RUN pip install -r requirements.txt
CMD ["./start.sh"]
